### ISSUE TITLE
Rebar3?

### ISSUE THREAD

**Issue by tsloughter** [stylefruits/rib#1]
Just ran into your slides and looked at your lib and noticed you are using rebar2, so I thought I'd just check if you knew about rebar3 or not :) http://www.rebar3.org/

You'll need to use https://github.com/blt/port_compiler#use-with-existing-dependency for compiling jiffy but the rest should work fine. Also, jiffy and elli are both on https://hex.pm/, I don't see ejsonpath so that'd have to stay as a git dep.

**Comment by jstepien** [comment]
Thanks a lot for the hint @tsloughter! We'll take a look and see how rebar3 can help us here.

**Comment by jstepien** [comment]
Ported to rebar3 by @Leonidas-from-XIV in 2bba76449c2bac2252f4225747afc1f6827412b4. Thanks for the suggestion @tsloughter!

**Comment by tsloughter** [comment]
Awesome, hope you like it :)
